[project]
name = "fastmcp-demo-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Gurnoor Singh", email = "gur.farwaha2005@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "aiomysql>=0.3.2",
    "fastmcp>=4.0.10",
    "mysql-connector-python",
    "python-dotenv",
]

[project.scripts]
fastmcp-demo-server = "fastmcp_demo_server:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
